# Site
name: 'Geoff Whiting'
description: 'This is the home of Geoff Whiting, a Washington DC writer and content marketer.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
url: 'http://127.0.0.1:4000'
baseurl: ''
# url: 'https://whaleen.github.io/geoff/'
# baseurl: 'https://whaleen.github.io/geoff/'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-category-pages

authors:
    geoff:
      name:           Geoff Whiting
      site:           https://www.ghiting.net
      avatar:         /assets/images/geoff-avatar.jpg
      bio:            "Hi, I am Geoff Whiting, a writer and content marketer in Washington DC."
      email:          geoff@gwhiting.com
      twitter:        https://twitter.com/

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: geoff
      avatar: /assets/images/geoff-avatar.jpg

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
