# Site
name: 'Geoff Whiting'
description: 'This is the home of Geoff Whiting, a Washington DC writer and content marketer.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: '/mundana-theme-jekyll'
disqus: 'demowebsite'
email: 'example@example.com'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

authors:
    geoff:
      name:           Geoff Whiting
      site:           https://www.ghiting.net
      avatar:         /assets/images/geoff-avatar.jpg
      bio:            "Hi, I am Geoff Whiting, a writer and content marketer in Washington DC."
      email:          geoff@gwhiting.com
      twitter:        https://twitter.com/

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: geoff
      avatar: /assets/images/geoff-avatar.jpg

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
