---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: document
  path: _data/client_testimonial.yml
  label: Client Testimonials
  match: "**/*"
- type: document
  path: _data/client_carousel.yml
  label: Client Carousel
- type: document
  path: _data/article_footer.yml
  label: Article Footer
- type: jekyll-posts
  label: Articles
  create: all
  templates:
  - blog-post
- type: document
  path: _data/information.yml
  label: Contact Information
- type: document
  path: _data/welcome.yml
  label: Homepage Greeting
upload_dir: assets/images
public_path: "/assets/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
