# config.yml

backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: 'assets/uploads'

# Collections  with Netlify Settings
collections:
  - name: 'blog'
    create: true # Allow users to create new documents in this collection
    label: 'Blog'
    folder: '_posts/'
    identifier_field: Title
    fields:
      - { name: Title }
      - {label: "Title", name: "name", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}

  - label: "Project"
    name: "project"
    create: true # Allow users to create new documents in this collection
    folder: "_posts"
    filter: {field: "type", value: "project"}
    fields:
      - {label: "Lenguaje", name: "language", widget: "select", options: ["en", "es"]}
      - {label: "Titulo", name: "title", widget: "string"}
      - {label: "Contenido", name: "body", widget: "markdown"}
