# config.yml

backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: 'assets/uploads'

# Collections  with Netlify Settings
collections:
  - name: 'post'
    create: true # Allow users to create new documents in this collection
    label: 'Post'
    folder: '_posts/'
    identifier_field: Title
    filter: {field: "section", value: "blog"}
    fields:
      - {name: Title }
      - {label: "Section", name: "section", widget: "select", options: ["blog", "project"]}
      - {label: "Title", name: "name", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
